name: GH-ACTION-BUILD-AND-PUBLISH
on: push

jobs:
  GH-ACTION-BUILD:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}        

      - name: Run bash script
        run: |
          echo "Running bash script..."
          chmod +x ./scripts/build.sh
          ./scripts/build.sh
          echo "Bash script completed."
