name: GH-ACTION-TEST
on: push

jobs:
  GH-ACTION-TEST:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Full history for accurate git diff

      - name: Find changed Dockerfile directories
        id: detect
        run: |
          echo "Finding changed services..."

          # Ensure we have the base to compare
          BASE=${{ github.event.before }}
          if [ -z "$BASE" ]; then
            echo "No previous commit; falling back to origin/main"
            BASE="origin/main"
            git fetch origin main
          fi

          # Get list of changed folders containing a Dockerfile
              awk -F/ '{print $1}' | \
              sort -u | \
              while read dir; do
          CHANGED_DIRS=$(git diff --name-only $BASE ${{ github.sha }} | \
              if [ -f "$dir/Dockerfile" ]; then
                  echo $dir
              fi
              done)

          echo "changed_dirs=$CHANGED_DIRS" >> $GITHUB_OUTPUT

      - name: Show changed services
        run: |
          echo "Changed services: ${{ steps.detect.outputs.changed_dirs }}"
